apiVersion: v2
name: amongus-discord
description: A Amongus Discord Helm chart for Kubernetes
version: 0.1.0
appVersion: 1.16.0
maintainers:
  - name: Lucca Pessoa
    email: luccapsm@gmail.com
icon: https://github.com/lpmatos/amongus-chart/blob/master/assets/Logo.jpg
sources:
  - https://github.com/lpmatos/amongus-chart
type: application
