apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-token
  namespace: {{ .Release.Namespace }}
  labels: {{- include "amongusdiscord.labels" . | nindent 4 }}
type: Opaque
data:
  discord-bot-token: {{ include "discord.bot.token" . | b64enc | quote }}
---
