apiVersion: v1
kind: Service
metadata:
  name: {{ include "amongusdiscord.name" . }}
  labels: {{- include "amongusdiscord.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: {{ include "amongusdiscord.name" . }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector: {{ include "amongusdiscord.selectorLabels" . | nindent 4 }}
---
